spring:
  datasource:
    url: jdbc:h2:file:./data/triage-db;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

# Swagger UI bude na /swagger-ui/index.html
server:
  port: 8080
